import type { Product } from "@/types";

/**
 * Initial catalogue (the 8 products that were hard-coded in the homepage).
 * Used by `scripts/seed.ts`. Fields id/views/timestamps are set by Mongo.
 */
export type SeedProduct = Omit<Product, "id" | "views" | "createdAt" | "updatedAt">;

export const SEED_PRODUCTS: SeedProduct[] = [
  { name: "Midnight Oud Reserve", slug: "midnight-oud-reserve", category: "PERFUME_MEN", price: 8500, description: "A bold expression of power. Dark oud and smoked leather that lingers for hours.", imageUrl: "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=600&q=80", thumbUrl: null, field1: "Saffron, Bergamot, Black Pepper", field2: "Aged Oud, Smoky Leather, Orris", field3: "Labdanum, Dark Amber, Vetiver", stock: 14, featured: true },
  { name: "Velvet Bloom Elixir", slug: "velvet-bloom-elixir", category: "PERFUME_WOMEN", price: 7800, description: "Bulgarian rose intertwines with warm sandalwood — the fragrance for a woman who commands every room.", imageUrl: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&q=80", thumbUrl: null, field1: "Lychee, Bergamot, Pink Pepper", field2: "Bulgarian Rose, Peony, Magnolia", field3: "Sandalwood, Cashmere, White Musk", stock: 11, featured: true },
  { name: "Emerald Grove", slug: "emerald-grove", category: "PERFUME_UNISEX", price: 5900, description: "Green tea, fern, and crisp iris unite in a composition that is simultaneously alive and contemplative.", imageUrl: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80", thumbUrl: null, field1: "Green Tea, Galbanum, Lemon Zest", field2: "Iris, Violet Leaf, Fern", field3: "Vetiver, White Cedar, Ambrette", stock: 20, featured: true },
  { name: "Luminous Glow Serum", slug: "luminous-glow-serum", category: "SKINCARE", price: 3200, description: "Vitamin C and hyaluronic acid brighten and plump skin for a glass-skin radiance.", imageUrl: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab12?w=600&q=80", thumbUrl: null, field1: "Vitamin C 15%, Niacinamide, Hyaluronic Acid", field2: "Brightening, Firming, Deep Hydration", field3: "Apply 2-3 drops morning and evening before moisturiser", stock: 25, featured: true },
  { name: "Noir Royale", slug: "noir-royale", category: "PERFUME_MEN", price: 5200, description: "Deep, commanding. Black pepper meets aged leather and tobacco.", imageUrl: "https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=600&q=80", thumbUrl: null, field1: "Black Pepper, Cardamom", field2: "Leather, Tobacco", field3: "Patchouli, Oakmoss", stock: 4, featured: false },
  { name: "Sable & Sel", slug: "sable-sel", category: "PERFUME_UNISEX", price: 6800, description: "Sand, salt, skin. A near-transparent marine structure grounded in warm driftwood.", imageUrl: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=600&q=80", thumbUrl: null, field1: "Sea Salt, Ozonic Accord, Lemon", field2: "Driftwood, Ambrette, Cashmeran", field3: "White Musk, Ambergris, Cedar", stock: 17, featured: false },
  { name: "Matte Velvet Foundation", slug: "matte-velvet-foundation", category: "MAKEUP", price: 2800, description: "Buildable, long-wear coverage that breathes — 24h matte finish that never feels cakey.", imageUrl: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80", thumbUrl: null, field1: "SPF 30, Hyaluronic Acid, Vitamin E", field2: "Full Coverage, Pore-minimising, Oil-control", field3: "Apply with brush or sponge, blend outward", stock: 30, featured: false },
  { name: "Silk Repair Mask", slug: "silk-repair-mask", category: "HAIRCARE", price: 1800, description: "Keratin and argan oil restore lustre and elasticity to damaged, over-processed hair.", imageUrl: "https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=600&q=80", thumbUrl: null, field1: "Keratin, Argan Oil, Biotin", field2: "Repair, Shine, Detangle, Strengthen", field3: "Apply post-shampoo, leave 5 min, rinse", stock: 0, featured: false },
];
